# Generated by Django 2.2.13 on 2020-07-02 21:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Result',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.FloatField(default=0.0)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.Student')),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.Test')),
            ],
        ),
        migrations.CreateModel(
            name='StudentResponse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ques', models.TextField()),
                ('ans', models.TextField()),
                ('status', models.BooleanField(default=False)),
                ('res', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='starttest.Result')),
            ],
        ),
    ]
